# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    concurrency:
      group: 'build'
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js for Windows
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run make
    - name: Get the verision from package.json
      run: echo "pkg_version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    - uses: sigstore/cosign-installer
    - name: Sign the build
      run: |
        cosign sign "out/make/squirrel.windows/x64/FTC-Remote-Debugger-$pkg_version Setup.exe"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: windows-latest
        path: out/make
