# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and package

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-latest

    concurrency:
      group: 'build-${{matrix.os}}'
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js for platform ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ matrix.os }}
        path: out/make
